### ISSUE TITLE
Wrong name in MyNft test case

### ISSUE THREAD

**Issue by hexcowboy** [alchemyplatform/alchemy-flow-contracts#10]
https://github.com/alchemyplatform/alchemy-flow-contracts/blob/e49278ab40e6d114c9b3cb1cc8824a8d8aa5d5d8/src/cadence/scripts/testGetNFTs.sh#L20-L23

This shouldn't be associated with Eternal :)

**Comment by niveda-krish** [comment]
Thanks for sending the fix :)
