### ISSUE TITLE
Q: Add adapter for metadata stored on IPFS (Rarible)

### ISSUE THREAD

**Issue by atapin** [alchemyplatform/alchemy-flow-contracts#22]
Hey folks,

I look for a way to form a `NFTData` structure for our case, when we store the actual meta on IPFS. On chain, we store e.g. `metaURI: ipfs://ipfs/QmThjic7hgsN1MfmxMtxU6nefWwSpqf9GTx9HfV2ArxRN4`. 
Is there a way to tell the Alchemy API fetch the data from IPFS?

**Comment by atapin** [comment]
Draft integration: #23

**Comment by niveda-krish** [comment]
Hey @atapin, I will send out a PR to add this field, we plan to call it tokenUri

**Comment by niveda-krish** [comment]
Added a new token_uri field which should help in cases where the data is offchain: https://github.com/alchemyplatform/alchemy-flow-contracts/commit/4640709c699796f91fde7b063e1e4d184b9db9c7
